version: 2

run:
  timeout: 5m
  tests: true

linters:
  # Use default linters
  disable-all: false
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

linters-settings:
  errcheck:
    # Ignore defer error checks
    ignore: fmt:.*,io/ioutil:^Read.*

issues:
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  # Exclude defer error checks
  exclude:
    - 'Error return value of .*Close.* is not checked'
    - 'Error return value of .*RemoveAll.* is not checked'
